services:
  testing:
    image: pollenrobotics/reachy2_testing:latest
    container_name: reachy2_testing
    privileged: true
    environment:
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.reachy_config:/home/reachy/.reachy_config_override
      - /dev:/dev
    group_add:
      - audio
    # allow interprocess comunication to handle alsa audio concurrent access
    ipc: host
    device_cgroup_rules:
      - 'c 189:* rmw' # rules for usb cam
    network_mode: "host"